bot:
  token: 974454071:AAEGMhxE5ltRKdI6kKi-elZpuZ_6-SVGvzY
  username: RPGIRLBot
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RPGIRL
    username: postgres
    password: 123
  jpa:
    generate-ddl: true