bot:
  token: secret
  username: RPGIRLBot
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rpgirl
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
